### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by kloetzl** [dnbaker/dashing#9]
As of `v0.1.1-38-g5ab9bec` a new clone and build fails with the following message.

```
bonsai/hll/vec/vec.h: In function ‘constexpr __m128i vec::_mm_mullo_epi64x(__m128i, uint64_t)’:
bonsai/hll/vec/vec.h:115:27: error: call to non-‘constexpr’ function ‘__m128i _mm_mullo_epi64(__m128i, __m128i)’
     return _mm_mullo_epi64(a, _mm_set1_epi64x(b));
```

(also bonsai/hll/vec/vec.h:119:30)

**Comment by dnbaker** [comment]
I saw that with one compiler version I was working with, but couldn’t reproduce it after reverting my fix (removing constexpr from those functions). Somehow the set1_epi64x functions weren’t seen as constexpr but only in a condition I couldn’t reproduce later, so I dismissed it as a fluke. I’ll push that early this morning when I can.

**Comment by kloetzl** [comment]
FYI: I am working on a Ubuntu 18.04 LTS with GCC 8.2.0.

**Comment by dnbaker** [comment]
This has been corrected.

**Comment by kloetzl** [comment]
Yeah, its fixed. (I get a ton of warning about functions which couldn't be inlined though.)
