### ISSUE TITLE
Can't build using gcc 5.4 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

### ISSUE THREAD

**Issue by ZekunYin** [dnbaker/dashing#21]
Hi Daniel,
When I tried to build dashing on my server, I got these errors:
```
In file included from src/dashing.cpp:8:0:
bonsai/hll/mh.h: In member function ‘sketch::minhash::HyperMinHash<T, Hasher>& sketch::minhash::HyperMinHash<T, Hasher>::operator+=(const sketch::minhash::HyperMinHash<T, Hasher>&)’:
bonsai/hll/mh.h:985:32: error: ‘max_fn16’ is not a member of ‘sketch::hll::detail::SIMDHolder’
                     do {*ptr = SIMDHolder::op(*ptr, *optr++);} while(++ptr != eptr); break;
                                ^
bonsai/hll/mh.h:987:17: note: in expansion of macro ‘CASE_U’
                 CASE_U(U16, max_fn16)
                 ^
bonsai/hll/mh.h:985:32: error: ‘max_fn32’ is not a member of ‘sketch::hll::detail::SIMDHolder’
                     do {*ptr = SIMDHolder::op(*ptr, *optr++);} while(++ptr != eptr); break;
                                ^
bonsai/hll/mh.h:988:17: note: in expansion of macro ‘CASE_U’
                 CASE_U(U32, max_fn32)
                 ^
bonsai/hll/mh.h:985:32: error: ‘max_fn64’ is not a member of ‘sketch::hll::detail::SIMDHolder’
                     do {*ptr = SIMDHolder::op(*ptr, *optr++);} while(++ptr != eptr); break;
                                ^
bonsai/hll/mh.h:989:17: note: in expansion of macro ‘CASE_U’
                 CASE_U(U64, max_fn64)
```
I'm not sure whether it has anything to do with gcc5.4. But the README says it has been tested using this version of gcc.

**Comment by dnbaker** [comment]
Hi, and thanks for reporting the issue!

It seems that I neglected to implement a feature for AVX512-enabled systems. I've corrected this [in this commit](https://github.com/dnbaker/sketch/commit/c230164eb2b4ae016d6f3de8d8a98a1c1803f79c) and propagated that change to Dashing's master branch.

Would you trying pulling from master and give that a shot?

If it fails to build, it may be failing to update the sketch submodule, which you could do manually by `cd bonsai/hll && git checkout master && git pull origin master && cd ../..`.

Hope this helps,

Daniel

**Comment by ZekunYin** [comment]
Hi Daniel,
Thanks for reply. I can successfully build dashing on another ubuntu 18.04 server with minor modification to `bonsai/hll/bbmh.h` in line 380. I changed `__m512i lsum = _mm256_set1_epi64(0)`  to `__m512i lsum = _mm512_set1_epi64(0)`. Due to that my ubuntu 16.04 server is temporary offline, I will try to build dashing using gcc5.4 again later. Your response really helps me a lot. Thanks again.
Best,
Zekun

**Comment by dnbaker** [comment]
Great find!

I've incorporated your change [here](https://github.com/dnbaker/sketch/commit/8ec80c4e8d48d27b1bf3404e46a08ff839e04964) in the sketch library, which version has been updated in the dashing main repository.

Thank you for your help, and don't hesitate to ask further.

Daniel

**Comment by ZekunYin** [comment]
Hi Daniel,
My ubuntu 16.04 server is finally online. But there are still some problems using gcc5.4 to compile dashing especially when using AVX512 reduce intrinsics. I just looked through the `x86intrin.h` and found that `reduce` related intrinsics were not supported even `AVX512F` flag enabled. I think maybe gcc5.4 is no longer the minimal version required by dashing. 
Best,
Zekun

**Comment by dnbaker** [comment]
Hi Zekun,

Can you provide the specific error? I haven't been able to reproduce it on my systems and I'd like to help, but the Skylake server I normally would test gcc5.4 on is under maintenance, though it should be available with AVX512F (unless perhaps you're KNCNI?) according to [Intel's Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=34,24,4656,3166,5228,5227,5271,3166,4666,6,4,3,4525,4525&text=_mm512_reduce_add_epi64).

**Comment by ZekunYin** [comment]
Hi Daniel,
I'm sorry that I didn't provide the specific errors. Unfortunately the ubuntu 16.04 server was offline again since last night. I will provide more detail when I can get access to it. I'm really sorry to occupy you so such time to deal with it. And thanks again.
Best,
Zekun

**Comment by dnbaker** [comment]
Hi,

I've been able to test on a skylake machine with gcc5.4.0. There were indeed issues with gcc5.4.0 and newer intrinsics, but now I've been able to build it. Can you give it another try?

To save the hassle, I'll need to make a binary release soon.

Thanks!

**Comment by ZekunYin** [comment]
Thanks a lot. I will try it soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ZekunYin** [comment]
Now dashing works well on ubuntu 16.04 with gcc5.4.0. 
Thanks so much.

**Comment by dnbaker** [comment]
Fantastic! I’ll close this for now, but feel free to reopen if you have further issues.
